### ISSUE TITLE
Error on tab navigation

### ISSUE THREAD

**Issue by fujimite** [2024-S1-W101-SoundScapeCity/project#3]
Uncaught runtime errors:
`ERROR
node is null
nextSibling@webpack-internal:///./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js:208:24
getNextHostNode@webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5839:12
patch@webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:4844:16
patchBlockChildren@webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5131:12
patchElement@webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5066:25
processElement@webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:4954:19
patch@webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:4876:25
componentUpdateFn@webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5402:14
run@webpack-internal:///./node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js:217:19
setupRenderEffect/instance.update@webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5433:16
callWithErrorHandling@webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:328:33
flushJobs@webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:517:30`

**Comment by hmmpher** [comment]
Fixed as of #1 fac9b24412900486bc0ad0bdf5ed47f54952035c
